### ISSUE TITLE
Constructor signature of School

### ISSUE THREAD

**Issue by isururathnayaka** [KRVPerera/SportsMeet#9]
"System.InvalidOperationException: 'A parameterless default constructor or one matching signature (System.Int64 id, System.String name, System.Int64 districtId) is required for SportsMeet.Models.School materialization'"
DataBase.cs: Line 61

Caused by removing districtId from School, and Schools' constructor.

Have to change SQL.

**Comment by KRVPerera** [comment]
Fixed
